add consumer3

diff --git a/k8s/consumer3/deployment.yaml b/k8s/consumer3/deployment.yaml
--- a/k8s/consumer3/deployment.yaml
+++ b/k8s/consumer3/deployment.yaml
@@ -68,24 +68,22 @@ data:
 
     trap 'handle_sigterm' SIGTERM
 
-    while true; do
-      echo "Waiting for message...\n"
-      if ! currentMessage=$(amqp-consume --url="$RABBITMQ_URL" -q "hello" -c 1 cat); then
-          echo "Error occurred during message consumption. Exiting...\n"
-          continue
-      fi
-      echo "Message received, processing: $currentMessage \n"
+    echo "Waiting for message...\n"
+    if ! currentMessage=$(amqp-consume --url="$RABBITMQ_URL" -q "hello" -c 1 cat); then
+        echo "Error occurred during message consumption. Exiting...\n"
+        continue
+    fi
+    echo "Message received, processing: $currentMessage \n"
 
-      i=1
-      while [ $i -le 120 ]; do
-          echo "Message $i"
-          sleep 1
-          i=$((i+1))
-      done
-      currentMessage=""
-      curl -X POST http://result-analyzer-service:8080/create/count -s
-      echo "Waiting for next message...\n"
+    i=1
+    while [ $i -le 120 ]; do
+        echo "Message $i"
+        sleep 1
+        i=$((i+1))
     done
+    currentMessage=""
+    curl -X POST http://result-analyzer-service:8080/create/count -s
+    echo "Waiting for next message...\n"
 ---
 apiVersion: keda.sh/v1alpha1
 kind: TriggerAuthentication
